### ISSUE TITLE
Blank values ​​during checkout[Bug]

### ISSUE THREAD

**Issue by geron74784** [FOSSBilling/Proxmox#10]
**Describe the bug**
Blank values ​​regarding the Proxmox server configuration during purchase

**Expected behavior**
ERROR "Order could not be activated after checkout due to error: VPS has not been created"

**Screenshots**
If applicable, add screenshots to help explain your problem.[[LINK]](https://imgur.com/a/A9op6nw)

**Additional context**
I have installed the latest version of FOSSBilling and the Proxmox module,

**Comment by tobsowo** [comment]
I experienced this too yesterday when I tried.

**Comment by geron74784** [comment]
Are you using XAMPP?

**Comment by tobsowo** [comment]
Yes.

**Comment by geron74784** [comment]
Try installing it with nginx on linux https://fossbilling.org/docs/getting-started/nginx/

**Comment by tobsowo** [comment]
Does using nginx resolved the issue for you?

**Comment by geron74784** [comment]
I can't install FOSSBilling on Linux

**Comment by geron74784** [comment]
No I just tried I think it's a API problem.

**Comment by geron74784** [comment]
Solved, Qemu has problems I used LXC and it worked!
