### ISSUE TITLE
[Task] Create dedicated Proxmox users for clients

### ISSUE THREAD

**Issue by yagiz-dev** [FOSSBilling/Proxmox#2]
Originally https://github.com/scith/BoxBilling_Proxmox/issues/1.

Clients should have their own Proxmox accounts, displaying the terminal iFrame using the root account might cause serious security issues.

**Comment by Anuril** [comment]
This will be in release 0.1.0.

**Comment by Anuril** [comment]
Has been implemented in #29, closing this issue
