### ISSUE TITLE
[Bug] error when activating the module

### ISSUE THREAD

**Issue by mezoology** [FOSSBilling/Proxmox#21]
**Describe the bug**
Error Code: #0

Component: Generic

You've received a generic error message: Interface "Box\InjectionAwareInterface" not found

**To Reproduce**
after installing the module and once activating it gives the error on the latest version (0.5.4)

**Expected behavior**
installing it successfully.

**Screenshots**
https://i.imgur.com/zjvNVhQ.png

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser firefox

**Comment by GwalexOfficial** [comment]
When will the bug be fixed?

**Comment by Anuril** [comment]
This has been patched here - https://github.com/FOSSBilling/Proxmox/commit/b10531d60733578a4b3a1ecffff08cb18c3db640

With FOSSBilling Version 0.5.5 it is working.
